/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.dev.jsonc --include-runtime=false --env-interface=DevEnv worker/v2/env.d.ts` (hash: 9d1fec330bad02eada9b487bcc08f3f5)
interface __BaseEnv_DevEnv {
	AGENT_MODEL: "gpt-4.1-mini";
	MCP_ALLOWED_HOSTS: "localhost,127.0.0.1,vlist-v02-dev.smileme.ai";
	LIST_DOCUMENT: DurableObjectNamespace<import("./index").ListDocumentDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ListDocumentDO";
	}
	interface Env extends __BaseEnv_DevEnv {}
}
interface DevEnv extends __BaseEnv_DevEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_MODEL" | "MCP_ALLOWED_HOSTS">> {}
}
